name: Terraform Apply/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Selecione a ação do Terraform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

# --- Declaração global, adicione as secrets ao seu repositório ---
env:
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION:            ${{ secrets.AWS_REGION }}
  GITHUB_TOKEN:          ${{ secrets.TERRAFORM_GITHUB_TOKEN }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -out=tfplan -input=false

  prepare:
    name: Prepare for Apply
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Clone & Zip Lambdas
        run: bash terraform/scripts/prepare.sh

  deploy:
    name: Apply or Destroy
    runs-on: ubuntu-latest
    needs:
      - plan
      - prepare
    steps:
      - name: Terraform Apply or Destroy
        working-directory: terraform
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve tfplan -var="github_token=${{ env.GITHUB_TOKEN }}"
          else
            terraform destroy -auto-approve -var="github_token=${{ env.GITHUB_TOKEN }}"
          fi
