name: Terraform Apply/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Selecione a ação do Terraform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION:            ${{ secrets.AWS_REGION }}
  PROJECT_NAME:          ${{ secrets.PROJECT_NAME }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -out=tfplan -input=false

      - name: Empty ECR repository and S3 bucket before destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          # Remove all images from ECR
          aws ecr list-images --repository-name $PROJECT_NAME --region $AWS_REGION \
            --query 'imageIds[*]' --output json | \
            jq -c '.[]' | \
            while read image; do
              aws ecr batch-delete-image --repository-name $PROJECT_NAME --region $AWS_REGION --image-ids "$image"
            done

          # Remove all videos from S3 bucket
          aws s3 rm s3://$PROJECT_NAME --region $AWS_REGION --recursive

      - name: Terraform Apply or Destroy
        working-directory: terraform
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -input=false -auto-approve tfplan
          else
            terraform destroy -auto-approve
          fi